# Generated by Django 5.2.2 on 2025-06-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('event_type', models.CharField(choices=[('photoshoot', 'Фотосъемка'), ('post', 'Пост в соцсети')], default='photoshoot', max_length=20, verbose_name='тип события')),
                ('start_datetime', models.DateTimeField(verbose_name='дата и время начала')),
                ('end_datetime', models.DateTimeField(verbose_name='дата и время окончания')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='весь день')),
                ('color', models.CharField(default='#3788d8', max_length=20, verbose_name='цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'ordering': ['start_datetime'],
            },
        ),
    ]
