# Generated by Django 5.2 on 2025-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время окончания'),
        ),
    ]
