# Generated by Django 5.2 on 2025-06-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_event_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='описание'),
        ),
    ]
