# Generated by Django 5.2.2 on 2025-06-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('location_type', models.CharField(choices=[('studio', 'Студия'), ('outdoor', 'Улица')], default='studio', max_length=10, verbose_name='тип локации')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='район')),
                ('street', models.CharField(max_length=255, verbose_name='улица')),
                ('building', models.CharField(max_length=50, verbose_name='дом')),
                ('website', models.URLField(blank=True, verbose_name='веб-сайт')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_public', models.BooleanField(default=False, help_text='Если отмечено, студия будет видна всем пользователям', verbose_name='публичная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'студия/локация',
                'verbose_name_plural': 'студии/локации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studios/', verbose_name='изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='подпись')),
                ('is_main', models.BooleanField(default=False, verbose_name='главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'изображение студии',
                'verbose_name_plural': 'изображения студий',
                'ordering': ['-is_main', 'created_at'],
            },
        ),
    ]
