# Generated by Django 5.2.2 on 2025-06-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('image', models.ImageField(upload_to='references/', verbose_name='изображение')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('source_url', models.URLField(blank=True, verbose_name='источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'референс',
                'verbose_name_plural': 'референсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'категория референсов',
                'verbose_name_plural': 'категории референсов',
                'ordering': ['name'],
            },
        ),
    ]
