# Generated by Django 5.2.2 on 2025-06-07 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL, verbose_name='фотограф'),
        ),
        migrations.AddField(
            model_name='referencecategory',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_categories', to=settings.AUTH_USER_MODEL, verbose_name='фотограф'),
        ),
        migrations.AddField(
            model_name='reference',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='references.referencecategory', verbose_name='категория'),
        ),
    ]
